/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMK TELKOM
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bar1 = new javax.swing.JTextField();
        bar2 = new javax.swing.JTextField();
        bar3 = new javax.swing.JTextField();
        diskonn = new javax.swing.JTextField();
        bar4 = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        proses = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAhasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 140, 30);

        jLabel2.setText("Diskon");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 260, 90, 30);

        jLabel4.setText("Harga Barang 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 100, 90, 30);

        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 90, 30);

        jLabel5.setText("Harga Barang 3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 180, 90, 30);

        jLabel6.setText("Harga Barang 4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 90, 30);

        bar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar1ActionPerformed(evt);
            }
        });
        getContentPane().add(bar1);
        bar1.setBounds(130, 100, 180, 30);

        bar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar2ActionPerformed(evt);
            }
        });
        getContentPane().add(bar2);
        bar2.setBounds(130, 140, 180, 30);

        bar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar3ActionPerformed(evt);
            }
        });
        getContentPane().add(bar3);
        bar3.setBounds(130, 180, 180, 30);

        diskonn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonnActionPerformed(evt);
            }
        });
        getContentPane().add(diskonn);
        diskonn.setBounds(130, 260, 180, 30);

        bar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar4ActionPerformed(evt);
            }
        });
        getContentPane().add(bar4);
        bar4.setBounds(130, 220, 180, 30);

        exit.setText("Keluar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(260, 310, 73, 23);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(70, 310, 73, 23);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(170, 310, 73, 23);

        TAhasil.setColumns(20);
        TAhasil.setRows(5);
        jScrollPane1.setViewportView(TAhasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 350, 220, 120);

        setSize(new java.awt.Dimension(411, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bar1ActionPerformed

    private void bar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bar2ActionPerformed

    private void bar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bar3ActionPerformed

    private void diskonnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonnActionPerformed

    private void bar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bar4ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        int br1 = Integer.parseInt(bar1.getText());
        int br2 = Integer.parseInt(bar2.getText());
        int br3 = Integer.parseInt(bar3.getText());
        int br4 = Integer.parseInt(bar4.getText());
        int diskon =Integer.parseInt(diskonn.getText());
        int total1;
        int total;
        int harga;
        
        harga = br1+br2+br3+br4;
        if (diskon == 0){
            total = harga;
        }
        else {
            total1=harga*diskon/100;
            total = harga - total1;
        }
        TAhasil.setText("Harga Barang 1 : "+br1+"\nharga Barang 2 : "+br2+"\nHarga Barang 3 : "+br3+""
                + "\nHarga Barang 4 : "+br4+""
                + "\nDiskon : "+diskon+"\nTotal Bayar : "+total);
    }//GEN-LAST:event_prosesActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        TAhasil.setText("");
        bar1.setText("");
        bar2.setText("");
        bar3.setText("");
        bar4.setText("");
        diskonn.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAhasil;
    private javax.swing.JTextField bar1;
    private javax.swing.JTextField bar2;
    private javax.swing.JTextField bar3;
    private javax.swing.JTextField bar4;
    private javax.swing.JTextField diskonn;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
